---
- name: Install a new server
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - common
    - jenkins
    - permissions
    - nginx
    - php-fpm
    - composer
    - firewall
    - password
